import { EmployeeSummary, MeetingRecord, DocumentRecord, StatusRecord } from "@/types";
import { CANONICAL_DEPARTMENTS, COMPANIES } from "./constants";

const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const addDays = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d;
};
const addMonths = (months: number) => {
  const d = new Date(today);
  d.setMonth(d.getMonth() + months);
  return d;
};

export const INITIAL_EMPLOYEES: EmployeeSummary[] = [
  {
    employeeKey: "EMP-001-AARAV",
    rowNumber: 2,
    fullName: "Aarav Sharma",
    employeeId: "AHL-1001",
    company: COMPANIES[0],
    designation: "HR Lead & Operations",
    department: "Human Resources (HR)",
    manager: "Executive Director",
    doj: iso(addMonths(-14)),
    dob: iso(new Date(1993, addDays(4).getMonth(), addDays(4).getDate())), // Birthday in 4 days
    gender: "Male",
    mobile: "+91 98201 12345",
    companyEmail: "aarav.sharma@americanhairline.com",
    personalEmail: "aarav.sharma93@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "12 Jan 2025, 10:15 AM" },
      { label: "Full Name", value: "Aarav Sharma" },
      { label: "Employee ID", value: "AHL-1001" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "HR Lead & Operations" },
      { label: "Department", value: "Human Resources (HR)" },
      { label: "Reporting Manager", value: "Executive Director" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-14)) },
      { label: "Total Years of Experience", value: "7.5 Years" },
      { label: "Company E-mail ID", value: "aarav.sharma@americanhairline.com" },
      { label: "Date of Birth", value: iso(new Date(1993, addDays(4).getMonth(), addDays(4).getDate())) },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "O+" },
      { label: "Aadhar Card Number", value: "4829 1938 9012" },
      { label: "PAN Number", value: "BSFPS9821A" },
      { label: "Permanent Address", value: "Flat 402, Royal Palms, Goregaon East, Mumbai - 400065" },
      { label: "Current Address", value: "Flat 402, Royal Palms, Goregaon East, Mumbai - 400065" },
      { label: "Mobile Number", value: "+91 98201 12345" },
      { label: "Personal E-mail ID", value: "aarav.sharma93@gmail.com" },
      { label: "Father’s Name", value: "Rajendra Sharma" },
      { label: "Mother’s Name", value: "Sunita Sharma" },
      { label: "Emergency Contact Name", value: "Sunita Sharma" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98201 54321" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "HDFC Bank" },
      { label: "Branch", value: "Andheri West" },
      { label: "Account Number", value: "50100482910492" },
      { label: "IFSC Code", value: "HDFC0000249" },
      { label: "Current Salary", value: "₹85,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "12%" },
      { label: "Short-term Goals", value: "Automate onboarding workflows and consolidate HR command center." },
      { label: "Core Strengths", value: "Talent acquisition, employee lifecycle operations, conflict resolution." },
      { label: "Resource Requirements", value: "Advanced HR analytics tool access and recruiting portal licenses." },
      { label: "Alignment with Company Vision", value: "100% committed to scaling AHL into India's premier hair aesthetics brand." },
      { label: "Primary Hobbies", value: "Badminton, Photography, Marathon running" },
      { label: "Company Assets", value: "MacBook Pro M2, AHL Access Card, Official SIM" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Aarav Sharma" },
      { label: "Date", value: iso(addMonths(-14)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_001/view" },
    ],
  },
  {
    employeeKey: "EMP-002-DIYA",
    rowNumber: 3,
    fullName: "Diya Patel",
    employeeId: "AHL-1002",
    company: COMPANIES[1],
    designation: "Senior Video Editor",
    department: "Video Editor",
    manager: "Aarav Sharma",
    doj: iso(addDays(-7)), // Exactly 7 days ago -> Onboarding 7D feedback DUE!
    dob: iso(new Date(1997, addDays(11).getMonth(), addDays(11).getDate())), // Birthday in 11 days
    gender: "Female",
    mobile: "+91 97690 98765",
    companyEmail: "diya.patel@alchemane.com",
    personalEmail: "patel.diya@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "",
    masterFields: [
      { label: "Timestamp", value: "19 Sep 2026, 02:40 PM" },
      { label: "Full Name", value: "Diya Patel" },
      { label: "Employee ID", value: "AHL-1002" },
      { label: "Company", value: "Alchemane (ALC)" },
      { label: "Current Designation", value: "Senior Video Editor" },
      { label: "Department", value: "Video Editor" },
      { label: "Reporting Manager", value: "Aarav Sharma" },
      { label: "Date of Joining (DOJ)", value: iso(addDays(-7)) },
      { label: "Total Years of Experience", value: "4 Years" },
      { label: "Company E-mail ID", value: "diya.patel@alchemane.com" },
      { label: "Date of Birth", value: iso(new Date(1997, addDays(11).getMonth(), addDays(11).getDate())) },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "B+" },
      { label: "Aadhar Card Number", value: "9832 1049 2201" },
      { label: "PAN Number", value: "CPMPD4920K" },
      { label: "Permanent Address", value: "B-201, Shanti Sadan, Vile Parle, Mumbai - 400057" },
      { label: "Current Address", value: "B-201, Shanti Sadan, Vile Parle, Mumbai - 400057" },
      { label: "Mobile Number", value: "+91 97690 98765" },
      { label: "Personal E-mail ID", value: "patel.diya@gmail.com" },
      { label: "Father’s Name", value: "Kirit Patel" },
      { label: "Mother’s Name", value: "Hansaben Patel" },
      { label: "Emergency Contact Name", value: "Kirit Patel" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 97690 11223" },
      { label: "Number of Siblings", value: "2" },
      { label: "Bank Name", value: "ICICI Bank" },
      { label: "Branch", value: "Santacruz" },
      { label: "Account Number", value: "001901592834" },
      { label: "IFSC Code", value: "ICIC0000019" },
      { label: "Current Salary", value: "₹55,000 / month" },
      { label: "Last Increment Year", value: "" },
      { label: "Increment Percentage", value: "" },
      { label: "Short-term Goals", value: "Master DaVinci Resolve color grading for clinical studio reels." },
      { label: "Core Strengths", value: "High-tempo video editing, sound design, social media storytelling." },
      { label: "Resource Requirements", value: "High-speed external SSD and calibrated monitor." },
      { label: "Alignment with Company Vision", value: "Delivering top-tier patient transformation video content." },
      { label: "Primary Hobbies", value: "Short filmmaking, Acoustic guitar" },
      { label: "Company Assets", value: "Studio iMac, Noise cancelling headphones" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Scooty" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Diya Patel" },
      { label: "Date", value: iso(addDays(-7)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_002/view" },
    ],
  },
  {
    employeeKey: "EMP-003-KABIR",
    rowNumber: 4,
    fullName: "Kabir Singh",
    employeeId: "AHL-1003",
    company: COMPANIES[0],
    designation: "AHL Technician Specialist",
    department: "AHL Technician",
    manager: "Floor Manager",
    doj: iso(addMonths(-12)), // Exactly 1-year completion due!
    dob: iso(new Date(1991, addDays(19).getMonth(), addDays(19).getDate())), // Birthday in 19 days
    gender: "Male",
    mobile: "+91 98199 44332",
    companyEmail: "kabir.singh@americanhairline.com",
    personalEmail: "kabir.hairtech@yahoo.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Sep 2025, 09:30 AM" },
      { label: "Full Name", value: "Kabir Singh" },
      { label: "Employee ID", value: "AHL-1003" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "AHL Technician Specialist" },
      { label: "Department", value: "AHL Technician" },
      { label: "Reporting Manager", value: "Floor Manager" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-12)) },
      { label: "Total Years of Experience", value: "6 Years" },
      { label: "Company E-mail ID", value: "kabir.singh@americanhairline.com" },
      { label: "Date of Birth", value: iso(new Date(1991, addDays(19).getMonth(), addDays(19).getDate())) },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "A+" },
      { label: "Aadhar Card Number", value: "3920 4819 1192" },
      { label: "PAN Number", value: "ASDPS3920L" },
      { label: "Permanent Address", value: "704, Sea Green Apts, Worli, Mumbai" },
      { label: "Current Address", value: "704, Sea Green Apts, Worli, Mumbai" },
      { label: "Mobile Number", value: "+91 98199 44332" },
      { label: "Personal E-mail ID", value: "kabir.hairtech@yahoo.com" },
      { label: "Father’s Name", value: "Harpreet Singh" },
      { label: "Mother’s Name", value: "Jaspreet Kaur" },
      { label: "Emergency Contact Name", value: "Jaspreet Kaur" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98199 00998" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "Axis Bank" },
      { label: "Branch", value: "Worli" },
      { label: "Account Number", value: "91801004829103" },
      { label: "IFSC Code", value: "UTIB0000004" },
      { label: "Current Salary", value: "₹48,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "10%" },
      { label: "Short-term Goals", value: "Train junior technicians and optimize custom hair unit turnaround." },
      { label: "Core Strengths", value: "Precision hair unit bonding, client consultations, scalp styling." },
      { label: "Resource Requirements", value: "Upgraded ventilation in studio clinic 2." },
      { label: "Alignment with Company Vision", value: "Upholding highest medical hygiene and customer satisfaction." },
      { label: "Primary Hobbies", value: "Fitness, Motorcycling" },
      { label: "Company Assets", value: "Clinic Tool Kit, Studio Aprons" },
      { label: "Dietary Preference", value: "Non-Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Bike" },
      { label: "Housing Status", value: "Rented Property" },
      { label: "Digital Signature", value: "Kabir Singh" },
      { label: "Date", value: iso(addMonths(-12)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_003/view" },
    ],
  },
  {
    employeeKey: "EMP-004-MEERA",
    rowNumber: 5,
    fullName: "Meera Iyer",
    employeeId: "AHL-1004",
    company: COMPANIES[2],
    designation: "Performance Marketing Lead",
    department: "Digital Marketing",
    manager: "Aarav Sharma",
    doj: iso(addDays(-15)), // 15 days ago -> Onboarding 15D feedback DUE!
    dob: iso(new Date(1995, addDays(27).getMonth(), addDays(27).getDate())), // Birthday in 27 days
    gender: "Female",
    mobile: "+91 98402 33441",
    companyEmail: "meera.iyer@ydigital.in",
    personalEmail: "meera.iyer.mktg@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "",
    masterFields: [
      { label: "Timestamp", value: "11 Sep 2026, 11:00 AM" },
      { label: "Full Name", value: "Meera Iyer" },
      { label: "Employee ID", value: "AHL-1004" },
      { label: "Company", value: "YDigital" },
      { label: "Current Designation", value: "Performance Marketing Lead" },
      { label: "Department", value: "Digital Marketing" },
      { label: "Reporting Manager", value: "Aarav Sharma" },
      { label: "Date of Joining (DOJ)", value: iso(addDays(-15)) },
      { label: "Total Years of Experience", value: "5 Years" },
      { label: "Company E-mail ID", value: "meera.iyer@ydigital.in" },
      { label: "Date of Birth", value: iso(new Date(1995, addDays(27).getMonth(), addDays(27).getDate())) },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "AB+" },
      { label: "Aadhar Card Number", value: "5501 9283 4819" },
      { label: "PAN Number", value: "AKKPI9284R" },
      { label: "Permanent Address", value: "Flat 12B, Palm Meadows, Chembur, Mumbai" },
      { label: "Current Address", value: "Flat 12B, Palm Meadows, Chembur, Mumbai" },
      { label: "Mobile Number", value: "+91 98402 33441" },
      { label: "Personal E-mail ID", value: "meera.iyer.mktg@gmail.com" },
      { label: "Father’s Name", value: "S. Ramanathan Iyer" },
      { label: "Mother’s Name", value: "Lakshmi Iyer" },
      { label: "Emergency Contact Name", value: "Lakshmi Iyer" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98402 99887" },
      { label: "Number of Siblings", value: "0" },
      { label: "Bank Name", value: "State Bank of India" },
      { label: "Branch", value: "Chembur" },
      { label: "Account Number", value: "30918293849" },
      { label: "IFSC Code", value: "SBIN0000301" },
      { label: "Current Salary", value: "₹72,000 / month" },
      { label: "Last Increment Year", value: "" },
      { label: "Increment Percentage", value: "" },
      { label: "Short-term Goals", value: "Reduce blended cost per acquisition across Meta & Google Ads." },
      { label: "Core Strengths", value: "Paid search, Meta Ads manager, conversion rate optimization." },
      { label: "Resource Requirements", value: "Agency dashboard credentials and Supermetrics subscription." },
      { label: "Alignment with Company Vision", value: "Driving predictable consultation bookings for all branches." },
      { label: "Primary Hobbies", value: "Reading behavioral economics, Gardening" },
      { label: "Company Assets", value: "ThinkPad X1, External Monitor" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Meera Iyer" },
      { label: "Date", value: iso(addDays(-15)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_004/view" },
    ],
  },
  {
    employeeKey: "EMP-005-ROHAN",
    rowNumber: 6,
    fullName: "Rohan Gupta",
    employeeId: "AHL-1005",
    company: COMPANIES[0],
    designation: "AI & Automation Engineer",
    department: "Artificial Intelligence (AI)",
    manager: "Aarav Sharma",
    doj: iso(addMonths(-6)), // 6-month milestone!
    dob: iso(new Date(1996, 2, 14)),
    gender: "Male",
    mobile: "+91 98111 22334",
    companyEmail: "rohan.gupta@americanhairline.com",
    personalEmail: "rohan.techai@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2026",
    masterFields: [
      { label: "Timestamp", value: "26 Mar 2026, 04:12 PM" },
      { label: "Full Name", value: "Rohan Gupta" },
      { label: "Employee ID", value: "AHL-1005" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "AI & Automation Engineer" },
      { label: "Department", value: "Artificial Intelligence (AI)" },
      { label: "Reporting Manager", value: "Aarav Sharma" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-6)) },
      { label: "Total Years of Experience", value: "3 Years" },
      { label: "Company E-mail ID", value: "rohan.gupta@americanhairline.com" },
      { label: "Date of Birth", value: "1996-03-14" },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "O+" },
      { label: "Aadhar Card Number", value: "8829 1928 3847" },
      { label: "PAN Number", value: "BGPGG8829F" },
      { label: "Permanent Address", value: "C-403, Oberoi Splendor, Powai, Mumbai" },
      { label: "Current Address", value: "C-403, Oberoi Splendor, Powai, Mumbai" },
      { label: "Mobile Number", value: "+91 98111 22334" },
      { label: "Personal E-mail ID", value: "rohan.techai@gmail.com" },
      { label: "Father’s Name", value: "Vikram Gupta" },
      { label: "Mother’s Name", value: "Meenakshi Gupta" },
      { label: "Emergency Contact Name", value: "Vikram Gupta" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 98111 55667" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "Kotak Mahindra Bank" },
      { label: "Branch", value: "Powai" },
      { label: "Account Number", value: "781029384910" },
      { label: "IFSC Code", value: "KKBK0000958" },
      { label: "Current Salary", value: "₹65,000 / month" },
      { label: "Last Increment Year", value: "2026" },
      { label: "Increment Percentage", value: "15%" },
      { label: "Short-term Goals", value: "Build conversational AI bot for consultation scheduling." },
      { label: "Core Strengths", value: "TypeScript, Python, LLM agents, workflow automation." },
      { label: "Resource Requirements", value: "Cloud GPU API credits and staging server." },
      { label: "Alignment with Company Vision", value: "Automating operational overhead to let clinical staff focus on clients." },
      { label: "Primary Hobbies", value: "Robotics, Sci-Fi literature" },
      { label: "Company Assets", value: "MacBook Pro M3 Max" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Bike" },
      { label: "Housing Status", value: "Rented Property" },
      { label: "Digital Signature", value: "Rohan Gupta" },
      { label: "Date", value: iso(addMonths(-6)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_005/view" },
    ],
  },
  {
    employeeKey: "EMP-006-ANANYA",
    rowNumber: 7,
    fullName: "Ananya Rao",
    employeeId: "AHL-1006",
    company: COMPANIES[0],
    designation: "Customer Relationship Manager",
    department: "Customer Service Executive",
    manager: "Executive Director",
    doj: iso(addMonths(-24)), // 2-year completion!
    dob: iso(new Date(1994, 7, 19)),
    gender: "Female",
    mobile: "+91 98222 33445",
    companyEmail: "ananya.rao@americanhairline.com",
    personalEmail: "ananya.rao@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Sep 2024, 11:20 AM" },
      { label: "Full Name", value: "Ananya Rao" },
      { label: "Employee ID", value: "AHL-1006" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "Customer Relationship Manager" },
      { label: "Department", value: "Customer Service Executive" },
      { label: "Reporting Manager", value: "Executive Director" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-24)) },
      { label: "Total Years of Experience", value: "6 Years" },
      { label: "Company E-mail ID", value: "ananya.rao@americanhairline.com" },
      { label: "Date of Birth", value: "1994-08-19" },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "B+" },
      { label: "Aadhar Card Number", value: "7720 1928 3849" },
      { label: "PAN Number", value: "AZPAR7720Q" },
      { label: "Permanent Address", value: "101, Sagar Darshan, Bandra West, Mumbai" },
      { label: "Current Address", value: "101, Sagar Darshan, Bandra West, Mumbai" },
      { label: "Mobile Number", value: "+91 98222 33445" },
      { label: "Personal E-mail ID", value: "ananya.rao@gmail.com" },
      { label: "Father’s Name", value: "Prabhakar Rao" },
      { label: "Mother’s Name", value: "Shalini Rao" },
      { label: "Emergency Contact Name", value: "Shalini Rao" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98222 00112" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "HDFC Bank" },
      { label: "Branch", value: "Bandra" },
      { label: "Account Number", value: "50100293849102" },
      { label: "IFSC Code", value: "HDFC0000019" },
      { label: "Current Salary", value: "₹60,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "11%" },
      { label: "Short-term Goals", value: "Establish customer VIP loyalty protocol." },
      { label: "Core Strengths", value: "Client escalation management, empathy, team mentorship." },
      { label: "Resource Requirements", value: "Zendesk multi-agent license." },
      { label: "Alignment with Company Vision", value: "Ensuring every consultation feels dignified and confidential." },
      { label: "Primary Hobbies", value: "Hindustani classical music, Yoga" },
      { label: "Company Assets", value: "Dell Latitude, iPhone 14" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Ananya Rao" },
      { label: "Date", value: iso(addMonths(-24)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_006/view" },
    ],
  },
  {
    employeeKey: "EMP-007-VIVAAN",
    rowNumber: 8,
    fullName: "Vivaan Mehta",
    employeeId: "AHL-1007",
    company: COMPANIES[1],
    designation: "Senior Graphic Designer",
    department: "Graphic Designer",
    manager: "Aarav Sharma",
    doj: iso(addMonths(-15)), // 1 year + 3 months milestone!
    dob: iso(new Date(1992, 11, 5)),
    gender: "Male",
    mobile: "+91 98333 44556",
    companyEmail: "vivaan.mehta@alchemane.com",
    personalEmail: "vivaan.creative@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Jun 2025, 03:00 PM" },
      { label: "Full Name", value: "Vivaan Mehta" },
      { label: "Employee ID", value: "AHL-1007" },
      { label: "Company", value: "Alchemane (ALC)" },
      { label: "Current Designation", value: "Senior Graphic Designer" },
      { label: "Department", value: "Graphic Designer" },
      { label: "Reporting Manager", value: "Aarav Sharma" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-15)) },
      { label: "Total Years of Experience", value: "5.5 Years" },
      { label: "Company E-mail ID", value: "vivaan.mehta@alchemane.com" },
      { label: "Date of Birth", value: "1992-12-05" },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "A+" },
      { label: "Aadhar Card Number", value: "6610 2938 4819" },
      { label: "PAN Number", value: "BNMPM6610T" },
      { label: "Permanent Address", value: "302, Sunrise Towers, Juhu, Mumbai" },
      { label: "Current Address", value: "302, Sunrise Towers, Juhu, Mumbai" },
      { label: "Mobile Number", value: "+91 98333 44556" },
      { label: "Personal E-mail ID", value: "vivaan.creative@gmail.com" },
      { label: "Father’s Name", value: "Suresh Mehta" },
      { label: "Mother’s Name", value: "Geeta Mehta" },
      { label: "Emergency Contact Name", value: "Suresh Mehta" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 98333 11223" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "Standard Chartered" },
      { label: "Branch", value: "Santacruz" },
      { label: "Account Number", value: "23401928374" },
      { label: "IFSC Code", value: "SCBL0036001" },
      { label: "Current Salary", value: "₹58,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "10%" },
      { label: "Short-term Goals", value: "Revamp physical store collateral and packaging design." },
      { label: "Core Strengths", value: "Branding, Adobe Illustrator, UI mockups, typography." },
      { label: "Resource Requirements", value: "Wacom Cintiq drawing tablet." },
      { label: "Alignment with Company Vision", value: "Modern aesthetic expression matching premium medical hairline restoration." },
      { label: "Primary Hobbies", value: "Sketching, Comic books, Cycling" },
      { label: "Company Assets", value: "Apple iMac 27-inch, Wacom Intuos" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Vivaan Mehta" },
      { label: "Date", value: iso(addMonths(-15)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_007/view" },
    ],
  },
  {
    employeeKey: "EMP-008-ISHITA",
    rowNumber: 9,
    fullName: "Ishita Kapoor",
    employeeId: "AHL-1008",
    company: COMPANIES[0],
    designation: "Accounts Manager",
    department: "Accounts",
    manager: "Executive Director",
    doj: iso(addMonths(-36)),
    dob: iso(new Date(1989, 4, 12)),
    gender: "Female",
    mobile: "+91 98444 55667",
    companyEmail: "ishita.kapoor@americanhairline.com",
    personalEmail: "ishita.fin@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Sep 2023, 01:10 PM" },
      { label: "Full Name", value: "Ishita Kapoor" },
      { label: "Employee ID", value: "AHL-1008" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "Accounts Manager" },
      { label: "Department", value: "Accounts" },
      { label: "Reporting Manager", value: "Executive Director" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-36)) },
      { label: "Total Years of Experience", value: "9 Years" },
      { label: "Company E-mail ID", value: "ishita.kapoor@americanhairline.com" },
      { label: "Date of Birth", value: "1989-05-12" },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "O+" },
      { label: "Aadhar Card Number", value: "9910 2938 1928" },
      { label: "PAN Number", value: "AIUPK9910S" },
      { label: "Permanent Address", value: "501, Green Acres, Lokhandwala, Andheri West, Mumbai" },
      { label: "Current Address", value: "501, Green Acres, Lokhandwala, Andheri West, Mumbai" },
      { label: "Mobile Number", value: "+91 98444 55667" },
      { label: "Personal E-mail ID", value: "ishita.fin@gmail.com" },
      { label: "Father’s Name", value: "Raman Kapoor" },
      { label: "Mother’s Name", value: "Neena Kapoor" },
      { label: "Emergency Contact Name", value: "Raman Kapoor" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 98444 00991" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "HDFC Bank" },
      { label: "Branch", value: "Lokhandwala" },
      { label: "Account Number", value: "50100928374910" },
      { label: "IFSC Code", value: "HDFC0000542" },
      { label: "Current Salary", value: "₹80,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "12%" },
      { label: "Short-term Goals", value: "Automate GST reconciliation and TDS quarterly filings." },
      { label: "Core Strengths", value: "Financial audit, GST/TDS compliance, budget forecasting." },
      { label: "Resource Requirements", value: "Tally Prime Multi-user license." },
      { label: "Alignment with Company Vision", value: "Robust financial hygiene across all clinics and studios." },
      { label: "Primary Hobbies", value: "Culinary arts, Traveling" },
      { label: "Company Assets", value: "HP EliteBook 840, Token Dongle" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Ishita Kapoor" },
      { label: "Date", value: iso(addMonths(-36)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_008/view" },
    ],
  },
  {
    employeeKey: "EMP-009-ARJUN",
    rowNumber: 10,
    fullName: "Arjun Nair",
    employeeId: "AHL-1009",
    company: COMPANIES[0],
    designation: "Senior CRR Consultant",
    department: "CRR",
    manager: "Floor Manager",
    doj: iso(addMonths(-9)),
    dob: iso(new Date(1993, 10, 8)),
    gender: "Male",
    mobile: "+91 98555 66778",
    companyEmail: "arjun.nair@americanhairline.com",
    personalEmail: "arjun.crr@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2026",
    masterFields: [
      { label: "Timestamp", value: "26 Dec 2025, 05:40 PM" },
      { label: "Full Name", value: "Arjun Nair" },
      { label: "Employee ID", value: "AHL-1009" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "Senior CRR Consultant" },
      { label: "Department", value: "CRR" },
      { label: "Reporting Manager", value: "Floor Manager" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-9)) },
      { label: "Total Years of Experience", value: "4.5 Years" },
      { label: "Company E-mail ID", value: "arjun.nair@americanhairline.com" },
      { label: "Date of Birth", value: "1993-11-08" },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "B+" },
      { label: "Aadhar Card Number", value: "4820 1928 3849" },
      { label: "PAN Number", value: "AMNPA4820B" },
      { label: "Permanent Address", value: "Sector 14, Vashi, Navi Mumbai" },
      { label: "Current Address", value: "Sector 14, Vashi, Navi Mumbai" },
      { label: "Mobile Number", value: "+91 98555 66778" },
      { label: "Personal E-mail ID", value: "arjun.crr@gmail.com" },
      { label: "Father’s Name", value: "Gopalan Nair" },
      { label: "Mother’s Name", value: "Radha Nair" },
      { label: "Emergency Contact Name", value: "Radha Nair" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98555 11990" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "Canara Bank" },
      { label: "Branch", value: "Vashi" },
      { label: "Account Number", value: "109283749102" },
      { label: "IFSC Code", value: "CNRB0001092" },
      { label: "Current Salary", value: "₹45,000 / month" },
      { label: "Last Increment Year", value: "2026" },
      { label: "Increment Percentage", value: "10%" },
      { label: "Short-term Goals", value: "Boost post-consultation retention by 20%." },
      { label: "Core Strengths", value: "Customer retention, patient empathy, aftercare management." },
      { label: "Resource Requirements", value: "Automated SMS reminder integration." },
      { label: "Alignment with Company Vision", value: "Building long-term trust and loyalty with hairline maintenance clients." },
      { label: "Primary Hobbies", value: "Cricket, Podcasts" },
      { label: "Company Assets", value: "iPad Air, Official SIM" },
      { label: "Dietary Preference", value: "Non-Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Bike" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Arjun Nair" },
      { label: "Date", value: iso(addMonths(-9)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_009/view" },
    ],
  },
  {
    employeeKey: "EMP-010-SARA",
    rowNumber: 11,
    fullName: "Sara Khan",
    employeeId: "AHL-1010",
    company: COMPANIES[2],
    designation: "Influencer Marketing Executive",
    department: "Influencer Marketing",
    manager: "Aarav Sharma",
    doj: iso(addDays(-30)), // 1-month feedback milestone!
    dob: iso(new Date(1998, 8, 2)),
    gender: "Female",
    mobile: "+91 98666 77889",
    companyEmail: "sara.khan@ydigital.in",
    personalEmail: "sara.influencer@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "",
    masterFields: [
      { label: "Timestamp", value: "27 Aug 2026, 12:00 PM" },
      { label: "Full Name", value: "Sara Khan" },
      { label: "Employee ID", value: "AHL-1010" },
      { label: "Company", value: "YDigital" },
      { label: "Current Designation", value: "Influencer Marketing Executive" },
      { label: "Department", value: "Influencer Marketing" },
      { label: "Reporting Manager", value: "Aarav Sharma" },
      { label: "Date of Joining (DOJ)", value: iso(addDays(-30)) },
      { label: "Total Years of Experience", value: "2 Years" },
      { label: "Company E-mail ID", value: "sara.khan@ydigital.in" },
      { label: "Date of Birth", value: "1998-09-02" },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "O-" },
      { label: "Aadhar Card Number", value: "6620 1928 3746" },
      { label: "PAN Number", value: "ASKPK6620M" },
      { label: "Permanent Address", value: "Flat 303, Star Tower, Andheri East, Mumbai" },
      { label: "Current Address", value: "Flat 303, Star Tower, Andheri East, Mumbai" },
      { label: "Mobile Number", value: "+91 98666 77889" },
      { label: "Personal E-mail ID", value: "sara.influencer@gmail.com" },
      { label: "Father’s Name", value: "Irfan Khan" },
      { label: "Mother’s Name", value: "Shabana Khan" },
      { label: "Emergency Contact Name", value: "Irfan Khan" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 98666 11224" },
      { label: "Number of Siblings", value: "2" },
      { label: "Bank Name", value: "HDFC Bank" },
      { label: "Branch", value: "Andheri East" },
      { label: "Account Number", value: "50100293840192" },
      { label: "IFSC Code", value: "HDFC0000128" },
      { label: "Current Salary", value: "₹42,000 / month" },
      { label: "Last Increment Year", value: "" },
      { label: "Increment Percentage", value: "" },
      { label: "Short-term Goals", value: "Onboard 15 celebrity micro-influencers for authentic testimonial series." },
      { label: "Core Strengths", value: "Negotiation, talent outreach, campaign briefing, reel production." },
      { label: "Resource Requirements", value: "Creator discovery tool subscription." },
      { label: "Alignment with Company Vision", value: "Destigmatizing hair restoration through relatable public personalities." },
      { label: "Primary Hobbies", value: "Fashion blogging, Pilates" },
      { label: "Company Assets", value: "MacBook Air M2, iPhone 15" },
      { label: "Dietary Preference", value: "Non-Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Scooty" },
      { label: "Housing Status", value: "Rented Property" },
      { label: "Digital Signature", value: "Sara Khan" },
      { label: "Date", value: iso(addDays(-30)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_010/view" },
    ],
  },
  {
    employeeKey: "EMP-011-ADITYA",
    rowNumber: 12,
    fullName: "Aditya Joshi",
    employeeId: "AHL-1011",
    company: COMPANIES[0],
    designation: "Inventory & Procurement Lead",
    department: "Inventory",
    manager: "Floor Manager",
    doj: iso(addMonths(-18)),
    dob: iso(new Date(1990, 6, 21)),
    gender: "Male",
    mobile: "+91 98777 88990",
    companyEmail: "aditya.joshi@americanhairline.com",
    personalEmail: "aditya.supply@gmail.com",
    employmentStatus: "Active",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Mar 2025, 10:00 AM" },
      { label: "Full Name", value: "Aditya Joshi" },
      { label: "Employee ID", value: "AHL-1011" },
      { label: "Company", value: "American Hairline (AHL)" },
      { label: "Current Designation", value: "Inventory & Procurement Lead" },
      { label: "Department", value: "Inventory" },
      { label: "Reporting Manager", value: "Floor Manager" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-18)) },
      { label: "Total Years of Experience", value: "6 Years" },
      { label: "Company E-mail ID", value: "aditya.joshi@americanhairline.com" },
      { label: "Date of Birth", value: "1990-07-21" },
      { label: "Gender", value: "Male" },
      { label: "Blood Group", value: "B+" },
      { label: "Aadhar Card Number", value: "5510 2938 1928" },
      { label: "PAN Number", value: "AOJPJ5510C" },
      { label: "Permanent Address", value: "201, Shrikant Apts, Thane West" },
      { label: "Current Address", value: "201, Shrikant Apts, Thane West" },
      { label: "Mobile Number", value: "+91 98777 88990" },
      { label: "Personal E-mail ID", value: "aditya.supply@gmail.com" },
      { label: "Father’s Name", value: "Madhav Joshi" },
      { label: "Mother’s Name", value: "Aparna Joshi" },
      { label: "Emergency Contact Name", value: "Aparna Joshi" },
      { label: "Relationship", value: "Mother" },
      { label: "Emergency Contact Number", value: "+91 98777 00119" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "Bank of Baroda" },
      { label: "Branch", value: "Thane West" },
      { label: "Account Number", value: "089102938491" },
      { label: "IFSC Code", value: "BARB0THANEW" },
      { label: "Current Salary", value: "₹50,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "10%" },
      { label: "Short-term Goals", value: "Zero out-of-stock incidents for critical Swiss lace hair units." },
      { label: "Core Strengths", value: "Warehouse audits, vendor management, supply chain forecasting." },
      { label: "Resource Requirements", value: "Barcode scanner and mobile inventory app." },
      { label: "Alignment with Company Vision", value: "Seamless clinical readiness every morning." },
      { label: "Primary Hobbies", value: "Hiking, Chess" },
      { label: "Company Assets", value: "Zebra Barcode Scanner, Dell Laptop" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Bike" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Aditya Joshi" },
      { label: "Date", value: iso(addMonths(-18)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_011/view" },
    ],
  },
  {
    employeeKey: "EMP-012-NISHA",
    rowNumber: 13,
    fullName: "Nisha Verma",
    employeeId: "AHL-1012",
    company: COMPANIES[1],
    designation: "Consultant Dermatologist",
    department: "Consultant",
    manager: "Executive Director",
    doj: iso(addMonths(-8)),
    dob: iso(new Date(1988, 3, 10)),
    gender: "Female",
    mobile: "+91 98888 99001",
    companyEmail: "dr.nisha@alchemane.com",
    personalEmail: "nisha.derma@gmail.com",
    employmentStatus: "Left",
    lastIncrementYear: "2025",
    masterFields: [
      { label: "Timestamp", value: "26 Jan 2026, 02:00 PM" },
      { label: "Full Name", value: "Nisha Verma" },
      { label: "Employee ID", value: "AHL-1012" },
      { label: "Company", value: "Alchemane (ALC)" },
      { label: "Current Designation", value: "Consultant Dermatologist" },
      { label: "Department", value: "Consultant" },
      { label: "Reporting Manager", value: "Executive Director" },
      { label: "Date of Joining (DOJ)", value: iso(addMonths(-8)) },
      { label: "Total Years of Experience", value: "8 Years" },
      { label: "Company E-mail ID", value: "dr.nisha@alchemane.com" },
      { label: "Date of Birth", value: "1988-04-10" },
      { label: "Gender", value: "Female" },
      { label: "Blood Group", value: "O+" },
      { label: "Aadhar Card Number", value: "9920 1928 3810" },
      { label: "PAN Number", value: "ABVPV9920E" },
      { label: "Permanent Address", value: "Penthouse 14, Sky Greens, Worli, Mumbai" },
      { label: "Current Address", value: "Penthouse 14, Sky Greens, Worli, Mumbai" },
      { label: "Mobile Number", value: "+91 98888 99001" },
      { label: "Personal E-mail ID", value: "nisha.derma@gmail.com" },
      { label: "Father’s Name", value: "Anil Verma" },
      { label: "Mother’s Name", value: "Kiran Verma" },
      { label: "Emergency Contact Name", value: "Anil Verma" },
      { label: "Relationship", value: "Father" },
      { label: "Emergency Contact Number", value: "+91 98888 22110" },
      { label: "Number of Siblings", value: "1" },
      { label: "Bank Name", value: "HDFC Bank" },
      { label: "Branch", value: "Worli" },
      { label: "Account Number", value: "50100928374102" },
      { label: "IFSC Code", value: "HDFC0000004" },
      { label: "Current Salary", value: "₹1,20,000 / month" },
      { label: "Last Increment Year", value: "2025" },
      { label: "Increment Percentage", value: "8%" },
      { label: "Short-term Goals", value: "Relocating abroad for fellowship." },
      { label: "Core Strengths", value: "Scalp biopsy, trichology diagnostics, PRP therapy." },
      { label: "Resource Requirements", value: "Dermatoscope setup." },
      { label: "Alignment with Company Vision", value: "Maintaining medical standards." },
      { label: "Primary Hobbies", value: "Classical dance, Literature" },
      { label: "Company Assets", value: "Return complete" },
      { label: "Dietary Preference", value: "Veg" },
      { label: "Political Background", value: "No" },
      { label: "Political Details", value: "" },
      { label: "Vehicle Ownership", value: "Car" },
      { label: "Housing Status", value: "Own Property" },
      { label: "Digital Signature", value: "Nisha Verma" },
      { label: "Date", value: iso(addMonths(-8)) },
      { label: "PDF Link", value: "https://drive.google.com/file/d/demo_emp_012/view" },
    ],
  },
];

export const INITIAL_MEETINGS: MeetingRecord[] = [
  {
    meetingId: "MTG-2026-0001",
    employeeKey: "EMP-001-AARAV",
    employeeId: "AHL-1001",
    employeeName: "Aarav Sharma",
    milestone: "1-year completion",
    meetingType: "Quarterly Review",
    scheduledDate: iso(addDays(-2)),
    meetingDate: iso(addDays(-2)),
    discussionNotes: "Conducted annual leadership alignment. Reviewed department KPIs, recruitment pipeline and upcoming team expansion for South Mumbai branch.",
    warningGiven: "No",
    actionTaken: "Approved HR assistant hiring budget for Q3.",
    nextFollowUpDate: iso(addDays(4)), // Due within 7 days!
    attachmentLink: "https://drive.google.com/file/d/review_aarav_annual/view",
    recordedBy: "Executive Director",
    recordStatus: "Completed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    meetingId: "MTG-2026-0002",
    employeeKey: "EMP-003-KABIR",
    employeeId: "AHL-1003",
    employeeName: "Kabir Singh",
    milestone: "1-year completion",
    meetingType: "Quarterly Review",
    scheduledDate: iso(today),
    meetingDate: iso(today),
    discussionNotes: "Performance review for clinic technician work. Exceptional patient satisfaction feedback and zero unit detachment complaints over last 6 months.",
    warningGiven: "No",
    actionTaken: "Promoted to Technician Specialist with 10% increment.",
    nextFollowUpDate: iso(addDays(14)),
    attachmentLink: "",
    recordedBy: "Aarav Sharma",
    recordStatus: "Completed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    meetingId: "MTG-2026-0003",
    employeeKey: "EMP-009-ARJUN",
    employeeId: "AHL-1009",
    employeeName: "Arjun Nair",
    milestone: "",
    meetingType: "Warning",
    scheduledDate: iso(addDays(-5)),
    meetingDate: iso(addDays(-5)),
    discussionNotes: "Addressed three consecutive delayed customer follow-up calls in CRM and unrecorded client consultations.",
    warningGiven: "Yes",
    actionTaken: "First formal counseling given. Daily check-in checklist instituted with floor manager.",
    nextFollowUpDate: iso(addDays(2)), // Due in 2 days!
    attachmentLink: "https://drive.google.com/file/d/warning_arjun_crm/view",
    recordedBy: "Aarav Sharma",
    recordStatus: "Open",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    meetingId: "MTG-2026-0004",
    employeeKey: "EMP-002-DIYA",
    employeeId: "AHL-1002",
    employeeName: "Diya Patel",
    milestone: "7-day feedback",
    meetingType: "Onboarding Feedback",
    scheduledDate: iso(today),
    meetingDate: "",
    discussionNotes: "Scheduled 7-day onboarding review to ensure studio editing workstation setup and media asset access.",
    warningGiven: "No",
    actionTaken: "Pending review completion.",
    nextFollowUpDate: iso(addDays(8)),
    attachmentLink: "",
    recordedBy: "Aarav Sharma",
    recordStatus: "Open",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    documentId: "DOC-2026-0001",
    employeeKey: "EMP-001-AARAV",
    employeeId: "AHL-1001",
    employeeName: "Aarav Sharma",
    documentType: "Joining Letter",
    documentStatus: "Verified",
    fileName: "Aarav_Sharma_Joining_Letter.pdf",
    driveFileId: "drive_file_aarav_jl",
    driveLink: "https://drive.google.com/file/d/drive_file_aarav_jl/view",
    notes: "Original signed copy archived in HR safe.",
    uploadedBy: "Admin HR",
    uploadedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    documentId: "DOC-2026-0002",
    employeeKey: "EMP-001-AARAV",
    employeeId: "AHL-1001",
    employeeName: "Aarav Sharma",
    documentType: "Policy Signing",
    documentStatus: "Verified",
    fileName: "Aarav_Sharma_Code_Of_Conduct.pdf",
    driveFileId: "drive_file_aarav_pol",
    driveLink: "https://drive.google.com/file/d/drive_file_aarav_pol/view",
    notes: "AHL NDA and clinical confidentiality signed.",
    uploadedBy: "Admin HR",
    uploadedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    documentId: "DOC-2026-0003",
    employeeKey: "EMP-002-DIYA",
    employeeId: "AHL-1002",
    employeeName: "Diya Patel",
    documentType: "Joining Letter",
    documentStatus: "Uploaded",
    fileName: "Diya_Patel_Offer_Letter.pdf",
    driveFileId: "drive_file_diya_jl",
    driveLink: "https://drive.google.com/file/d/drive_file_diya_jl/view",
    notes: "Awaiting final countersignature.",
    uploadedBy: "Aarav Sharma",
    uploadedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    documentId: "DOC-2026-0004",
    employeeKey: "EMP-012-NISHA",
    employeeId: "AHL-1012",
    employeeName: "Nisha Verma",
    documentType: "Relieving Letter",
    documentStatus: "Verified",
    fileName: "Dr_Nisha_Verma_Relieving_Letter.pdf",
    driveFileId: "drive_file_nisha_rel",
    driveLink: "https://drive.google.com/file/d/drive_file_nisha_rel/view",
    notes: "Full and final settlement completed.",
    uploadedBy: "Aarav Sharma",
    uploadedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_STATUSES: StatusRecord[] = [
  {
    employeeKey: "EMP-012-NISHA",
    employeeId: "AHL-1012",
    employeeName: "Nisha Verma",
    employmentStatus: "Left",
    lastWorkingDate: iso(addDays(-10)),
    exitReason: "Pursuing higher dermatological fellowship in the UK.",
    relievingLetterLink: "https://drive.google.com/file/d/drive_file_nisha_rel/view",
    deactivatedAt: iso(addDays(-10)),
    deactivatedBy: "Aarav Sharma",
    restoredAt: "",
    restoredBy: "",
    updatedAt: new Date().toISOString(),
  },
];
